-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 19:39:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema espace_etudiant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema espace_etudiant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `espace_etudiant` DEFAULT CHARACTER SET utf8 ;
USE `espace_etudiant` ;

-- -----------------------------------------------------
-- Table `espace_etudiant`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`news` (
  `news_ID` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `contenue` VARCHAR(45) NULL,
  `date_news` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  PRIMARY KEY (`news_ID`),
  INDEX `fk_news_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`usertype` (
  `id_user_type` INT NOT NULL,
  `role_user` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`user` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `user_type` VARCHAR(45) NULL,
  `classe_id` INT NOT NULL,
  `usertype_id_user_type` INT NOT NULL,
  PRIMARY KEY (`id`, `classe_id`),
  INDEX `fk_user_usertype1_idx` (`usertype_id_user_type` ASC) VISIBLE,
  CONSTRAINT `fk_user_usertype1`
    FOREIGN KEY (`usertype_id_user_type`)
    REFERENCES `espace_etudiant`.`usertype` (`id_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`classe` (
  `id` INT NOT NULL,
  `nom_classe` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classe_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_classe_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`matiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`matiere` (
  `id_matiere` INT NOT NULL,
  `nom_matiere` VARCHAR(45) NULL,
  PRIMARY KEY (`id_matiere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`note` (
  `id_note` INT NOT NULL,
  `id_etudiant` VARCHAR(45) NULL,
  `id_classe` VARCHAR(45) NULL,
  `note` FLOAT NULL,
  `id_matiere` VARCHAR(45) NULL,
  `matiere_id_matiere` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id_note`),
  INDEX `fk_note_matiere1_idx` (`matiere_id_matiere` ASC) VISIBLE,
  INDEX `fk_note_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  INDEX `fk_note_classe1_idx` (`classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_matiere1`
    FOREIGN KEY (`matiere_id_matiere`)
    REFERENCES `espace_etudiant`.`matiere` (`id_matiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `espace_etudiant`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`document` (
  `iddocumet_ID` INT NOT NULL,
  `document_name` VARCHAR(45) NULL,
  `document_type` VARCHAR(45) NULL,
  `upload_date` DATE NULL,
  `classe_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  PRIMARY KEY (`iddocumet_ID`),
  INDEX `fk_document_classe1_idx` (`classe_id` ASC) VISIBLE,
  INDEX `fk_document_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `espace_etudiant`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`news` (
  `news_ID` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `contenue` VARCHAR(45) NULL,
  `date_news` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  PRIMARY KEY (`news_ID`),
  INDEX `fk_news_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`document_has_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`document_has_classe` (
  `document_iddocumet_ID` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`document_iddocumet_ID`, `classe_id`),
  INDEX `fk_document_has_classe_classe1_idx` (`classe_id` ASC) VISIBLE,
  INDEX `fk_document_has_classe_document1_idx` (`document_iddocumet_ID` ASC) VISIBLE,
  CONSTRAINT `fk_document_has_classe_document1`
    FOREIGN KEY (`document_iddocumet_ID`)
    REFERENCES `espace_etudiant`.`document` (`iddocumet_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_has_classe_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `espace_etudiant`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`user_has_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`user_has_note` (
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  `note_id_note` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_classe_id`, `note_id_note`),
  INDEX `fk_user_has_note_note1_idx` (`note_id_note` ASC) VISIBLE,
  INDEX `fk_user_has_note_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_note_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_note_note1`
    FOREIGN KEY (`note_id_note`)
    REFERENCES `espace_etudiant`.`note` (`id_note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `espace_etudiant`.`news_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espace_etudiant`.`news_has_user` (
  `news_news_ID` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_classe_id` INT NOT NULL,
  PRIMARY KEY (`news_news_ID`, `user_id`, `user_classe_id`),
  INDEX `fk_news_has_user_user1_idx` (`user_id` ASC, `user_classe_id` ASC) VISIBLE,
  INDEX `fk_news_has_user_news1_idx` (`news_news_ID` ASC) VISIBLE,
  CONSTRAINT `fk_news_has_user_news1`
    FOREIGN KEY (`news_news_ID`)
    REFERENCES `espace_etudiant`.`news` (`news_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_has_user_user1`
    FOREIGN KEY (`user_id` , `user_classe_id`)
    REFERENCES `espace_etudiant`.`user` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
